### PR TITLE
Remove node_modules from repository.

### LINKED ISSUE #3: node_modules is committed and missing from .gitignore
You should rely on `package.json` and add `node_modules` to `.gitignore`.

### PR DESCRIPTION
**Pull request by binki**
Added node_modules to .gitignore.

To restore modules after cloning the repository, simply run npm install
with no arguments.

Fixes #3.

### CODE REVIEW

**Comment by vzhou842** [comment]
This is a good thought, but we already had a discussion about this way back in the early days of the repo.

There are 2 main reasons we keep `node_modules` in the git repo:

* We have made a tiny but important modification to one of our dependencies that would be erased by a fresh `npm install`

* Running `npm install` every time could potentially break production without us having a chance to catch it. If one of our dependencies were to update something that broke something for us, we might not find it until we run `npm install` in production. By keeping `node_modules` in our source control, we can control exactly what it looks like every time and update individual dependencies as we choose at our own pace.

**Comment by binki** [comment]
> * Running `npm install` every time could potentially break production without us having a chance to catch it. 

Then you can pin the exact version of the dependency using `=1.2.3` syntax in `package.json`.

> * We have made a tiny but important modification to one of our dependencies that would be erased by a fresh npm install

This is really unfortunate. You should work with upstreams to either fix the bug or provide the necessary extensibility point you need. If you talk with upstreams, they may have suggestions for different ways to accomplish what you're trying to do too. If that really is not feasible, just fork the repo on GitHub and use a git hash dependency to the revision where you modified the dependency. `node_modules` is not a place to put custom code. Other people will assume it is temporary data which can be restored via `npm install` even when it's been committed to the git repo this way.

**Comment by binki** [comment]
> * We have made a tiny but important modification to one of our dependencies that would be erased by a fresh `npm install`

@vzhou842  What is this modification? When I use `npm install` after pinning `"socket.io-client": "=1.7.2"` I appear to get the same code in `node_modules` (excluding the keys `npm` sets in `package.json` files when installing stuff). Also, https://github.com/kpgbrink/generalsIO_Bot_KPG seems to run fine after merging this PR into it. It seems that you never actually made a critical change to any dependencies…

**Comment by vzhou842** [comment]
Maybe I'm wrong and we ended up reverting the change or overriding it - in any case, I don't see any major benefit to excluding `node_modules` from the repo (feel free to elaborate if you feel strongly on this). Sure, it bloats the repo a little, but it's a long way from becoming too large, so I'm not concerned about that. Plus, it removes `npm` as a dependency for the project - even if `npm` has issues or a certain `node_module` gets removed from `npm`, cloning the repo will still give you a fully functional project.

**Comment by binki** [comment]
I like to avoid including/bundling dependencies in repositories because it adds noise to the VCS. Ideally, the VCS’s history will only contain code written for that project. If you include other stuff, the repository size will grow needlessly too.

Also, if someone clones the tutorial as a starting point and wants to add a package from `npm` to use in their bot, git will suddenly show a bunch of changes in the `node_modules` directory. If you use npm as intended, only the changes actually relevant to the project (e.g., the modified `"dependencies"` key in `package.json` itself) will be up for commit.

I think that putting `node_modules` in your `.gitignore` and committing `package.json` is the current best practice and just what people expect when looking at a node-based project.

**Comment by vzhou842** [comment]
Ohh wait somehow I thought this was a PR for the actual (private) generals.io repository itself - I just realized this is the Node.js Bot Example repo. In this case it probably does make sense to go ahead with this. Sorry for the confusion, thanks for your patience.

**Comment by binki** [comment]
Ah. No problem! Now some of your earlier comments make a bit more sense ;-).

Thanks!

**Pull request merged**
